[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=/root/.config/qt6ct/colors/zexos.conf
icon_theme=breeze-dark

[Fonts]
general="Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
fixed="JetBrainsMono Nerd Font,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
