include themes/noctalia.conf
font_family JetBrainsMono Nerd Font
font_size 12
background_opacity 0.85

# Launch zsh in Kitty specifically (system login shell remains fish)
shell /usr/bin/zsh

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
