color0 #180934
color1 #fd4663
color2 #9167e4
color3 #c951e1
color4 #e151b0
color5 #b193ec
color6 #dd92ec
color7 #f2f2f3
color8 #645e72
color9 #fd4663
color10 #9167e4
color11 #c951e1
color12 #e151b0
color13 #b193ec
color14 #dd92ec
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #180934
background            #180934
foreground            #f2f2f3
selection_foreground  #b1afb6
selection_background  #1f0c45
active_border_color   #9167e4
inactive_border_color #1f0c45
url_color             #9167e4

active_tab_foreground   #1d1825
active_tab_background   #9167e4
inactive_tab_foreground #b1afb6
inactive_tab_background #1f0c45
cursor_trail_color      #b1afb6
