color0 #2b143e
color1 #fd4663
color2 #ac67e4
color3 #d65cd1
color4 #cf6394
color5 #c493ec
color6 #e996e5
color7 #f2f2f3
color8 #696170
color9 #fd4663
color10 #ac67e4
color11 #d65cd1
color12 #cf6394
color13 #c493ec
color14 #e996e5
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #200f2f
background            #200f2f
foreground            #f2f2f3
selection_foreground  #b3afb6
selection_background  #2b143e
active_border_color   #ac67e4
inactive_border_color #2b143e
url_color             #ac67e4

active_tab_foreground   #1f1825
active_tab_background   #ac67e4
inactive_tab_foreground #b3afb6
inactive_tab_background #2b143e
cursor_trail_color      #b3afb6
