-- ZeXOS — Hyprland main file
--
-- Hyprland is a third window manager you can pick at the login screen.
-- niri and Mango put windows side by side on a strip that scrolls; Hyprland
-- here tiles them instead: every new window splits the space of the one
-- you are in, so all windows on a workspace are always in view. Keys,
-- looks and the two desktop shells are the same as in niri.
--
-- This file only pulls in the smaller files in cfg/, one per topic.
-- Change things in those files, not here.
-- Full option list: https://wiki.hypr.land/Configuring/

-- Don't show the "this config was made for you" warning bar.
hl.config({ autogenerated = false })

require("cfg.animation")
require("cfg.autostart")
require("cfg.keybinds")
require("cfg.input")
require("cfg.layout")
require("cfg.rules")
require("cfg.misc")
require("cfg.overview")

-- The animation style you picked with `zexos-motion`, if you changed it.
-- Comes after cfg/animation.lua so it wins. Don't edit it by hand.
pcall(require, "motion")

-- Colours made from your wallpaper. Noctalia writes noctalia.lua on its
-- own, so don't edit that file. It comes after layout.lua so its colours
-- win. (Noctalia looks for the text require("noctalia") in this file and
-- adds it at the end if it is missing, so keep this line as it is.)
pcall(function() require("noctalia").apply_theme() end)

-- When you use DankMaterialShell instead, `zshell` writes this file so it
-- loads DMS's wallpaper colours, which then win over Noctalia's. With
-- Noctalia it is only a comment. Don't edit it by hand.
pcall(require, "shell-colors")

-- Mouse pointer look
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")

-- Your screens (see the file)
require("monitors")
