$primary = rgb(9167e4)
$surface = rgb(180934)
$secondary = rgb(c951e1)
$error = rgb(fd4663)
$tertiary = rgb(e151b0)
$surface_lowest = rgb(0c051a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
