# Installs the ZeXOS desktop with the picked compositors and shells.
---
dontChroot: true
timeout: 7200
i18n:
    name: "Installing the ZeXOS desktop"
script:
    - command: "/usr/local/bin/zexos-calamares-finish ${ROOT} ${USER} \"${gs[packagechooser_compositors]}\" \"${gs[packagechooser_shells]}\""
      timeout: 7200
