---
efi:
    mountPoint: "/boot"
    recommendedSize: 1024MiB
    minimumSize: 512MiB
    label: "EFI"
userSwapChoices: [ none, small, file ]
initialSwapChoice: none
drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
initialPartitioningChoice: erase
defaultFileSystemType: "btrfs"
availableFileSystemTypes: [ "btrfs", "ext4", "xfs" ]
enableLuksAutomatedPartitioning: false
partitionLayout:
    - name: "root"
      filesystem: "unknown"
      mountPoint: "/"
      size: 100%
