# Installs base Arch onto the new disk (official Arch repos only).
---
dontChroot: true
timeout: 3600
verbose: true
i18n:
    name: "Installing Arch Linux base"
script:
    - command: "/usr/local/bin/zexos-pacstrap ${ROOT}"
      timeout: 3600
