---
units:
    - name: NetworkManager
      action: enable
      mandatory: true
    - name: systemd-timesyncd
      action: enable
      mandatory: false
    - name: fstrim.timer
      action: enable
      mandatory: false
