# systemd-boot for now; more bootloaders later.
---
dontChroot: true
timeout: 900
i18n:
    name: "Setting up the boot loader"
script:
    - command: "/usr/local/bin/zexos-boot-setup ${ROOT}"
      timeout: 900
