---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false
showDonateUrl: false
requirements:
    requiredStorage: 30
    requiredRam: 2.0
    internetCheckUrl: https://github.com
    check: [ storage, ram, power, internet, root, screen ]
    required: [ storage, ram, internet, root ]
geoip:
    style: "none"
languageIcon: languages
